#!/usr/bin/perl
#
# This script export objects to stdout
# in this format:
#
#      mac,ip,hostname
#
#


use warnings;
use strict;

use EBox;
use EBox::Global;

EBox::init();


my $obj = EBox::Global->modInstance('network');


foreach my $object (@{$obj->objects}) {
  my $obj_desc = $obj->objectDescription($object->{id});
  print "$obj_desc\n";

  my $members = $obj->objectMembers($object->{id});
  foreach my $member (@{$members}) {
    my $mac = $member->{macaddr};
    defined($mac) or next;
    ($mac ne "") or next;


    my $address = $member->{ipaddr};
    $address =~ s/\/32//;
    my $name = $member->{name};
    print "  $mac,$address,$name\n";
  }
}


1;

